### ISSUE TITLE
proplem 

### ISSUE THREAD

**Issue by ibrahimashraf** [Soundnode/soundnode-website#1]
Hey how r u ? i got some bugs when i opened the soundnode app it told me authenticating with account and not doing any thing i closed it and opened it with compatibility windows 7 it opened now 
but the this the first time to  have problem with slow loading and it is not my connection and still have the problem about resize the window but not when open and close i tried to resize it and the result was  
screenshot
[http://prntscr.com/9xicca](url)

at the end sorry for bad english.
Ibrahim Ashrf(Egypt)

**Comment by weblancaster** [comment]
@ibrahimashraf try remove the download you have and download a new zip from the website. also please use https://github.com/Soundnode/soundnode-app/issues to report issues, check if anyone is having the same issue you are having
