### ISSUE TITLE
Include title of application in header

### ISSUE THREAD

**Issue by grant-h** [Soundnode/soundnode-website#5]
Upon visiting the Soundnode website, it is not apparent what the title of this Application is as there is no name on the header.

Here is something quick I did in inspector:

``` html
<div id="soundnode-title" style="float: left;margin: 0.8em 0 0 1.3em;color: black;">
     <h1 style="color: black;font-size: 2.5em;">Soundnode</h1>
</div>
```

<img width="340" alt="screen shot 2016-04-12 at 4 05 01 pm" src="https://cloud.githubusercontent.com/assets/3030665/14473908/65a15926-00c8-11e6-94aa-5fbe72fec437.png">

Obviously `style` wont be used, but as the website is out of date on Github, I figured I wouldn't make a PR.

**Comment by weblancaster** [comment]
This is not the repository for the desktop app but for the website.

Although I would think people would know what desktop app is open.

**Comment by grant-h** [comment]
Actually this was relating to the old website design (there was no "Soundnode" text anywhere on the page). Not relevant any more

**Comment by weblancaster** [comment]
Yep I know.
